default:
  image: haskell
  cache:
    paths:
      - .cabal

variables:
  CABAL_DIR: .cabal
  CABAL_BUILDDIR: .cabal/dist

stages:
  - build
  - test

build:
  script:
    - cabal build
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_TAG

test:
  script:
    - cabal test
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_TAG
